### ISSUE TITLE
Not working on JSX files.

### ISSUE THREAD

**Issue by mrbodich** [Hirse/brackets-outline-list#68] opened 2016-11-10 08:49 UTC
JSX is similar to JS. Please, add JSX support just like JS copy, the same. Thanks.

**Comment by Hirse** [comment] 2016-11-10 08:52
Please specify the version you are using and provide and example file and the desired output. Thanks.

**Comment by mrbodich** [comment] 2016-11-10 09:06
I am using 0.7.0, I think the latest. Brackets 1.7.0.
Here is an example of JSX file. JSX is also javascript language but with support of Adobe additional functions needed for Photoshop app or Illustrator. It is absolutely the same with JS. Result should be the same with JS files, showing functions list. So please just make a copy of JS language for JSX files, it will be enough I guess, or make JS language affect *.jsx files also. Thanks.
[temp.jsx.zip](https://github.com/Hirse/brackets-outline-list/files/582878/temp.jsx.zip)

**Comment by mrbodich** [comment] 2016-11-11 07:34
Tell me please, is it possible to make this improvement?

**Comment by Hirse** [comment] 2016-11-13 22:57
Yes, it is possible to make that improvement.
No, JSX is not absolutely the same as JS, it has an extended syntax. So, not all JS parser will work on JSX.
However, I was looking into replacing my JS parser anyway, so I will look into JSX support.

**Comment by Hirse** [comment] 2016-11-13 23:18
Also, this is a duplicate of #65.

**Closed by Hirse** 2016-11-13 23:18 UTC
Labels: enhancement

**Comment by mrbodich** [comment] 2016-11-14 06:54
Thank you very much! Works great, it really helps now.
